sudo: required
services:
  - docker

before_install:
  - docker build -t adidi/react-test -f ./client/Dockerfile.dev ./client


script:
  - docker run -e CI=true adidi/react-test npm test -- --coverage

after_success:
  - docker build -t adidi/multi-client ./client
  - docker build -t adidi/multi-nginx ./nginx
  - docker build -t adidi/multi-server ./server
  - docker build -t adidi/multi-worker ./worker

  # log in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push adidi/multi-client
  - docker push adidi/multi-nginx
  - docker push adidi/multi-server
  - docker push adidi/multi-worker